spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: 3252881064008f
    password: d4593030a9ec03
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


logging:
  level:
    root: INFO
    br.com.nicolas: DEBUG

server:
  port: 8081